### ISSUE TITLE
Training Code

### ISSUE THREAD

**Issue by AvivNavon** [glory20h/VoiceLDM#2]
Thanks for this awesome work!
Are you planning on releasing the training code?

**Comment by glory20h** [comment]
Hi!
Thank you for your interest in VoiceLDM.

If there are enough people interested in the training code, I could consider working on releasing the training code as well.

Maybe you(or others watching this message) could react with a emoji to let me know whether you need the training code as well. If there's more than 5, I will spare some time to work on the training code. I appreciate your feedback!

**Comment by Ming-er** [comment]
Now there are more than 5 replies.

**Comment by glory20h** [comment]
Hi AvivNavon and everyone,

I'm glad to share that I've managed to spare some time to work on the training code and recently committed the updated version. Thanks for your patience and for showing interest!

Feel free to open new issues or ask any questions if something is unclear or if you run into any problems!

**Comment by AvivNavon** [comment]
Thank you @glory20h !
